USE E_Commerce;
GO

--1. Total sales amount generated by each store
CREATE OR ALTER VIEW vw_total_sales_per_store AS
SELECT s.store_key,
       SUM(f.total_price) AS total_sales
FROM fact_table f
JOIN store_dim s ON f.store_key = s.store_key
GROUP BY s.store_key;
GO

--2. Total sales amount for each month
CREATE OR ALTER VIEW vw_monthly_sales AS
SELECT t.month,
       SUM(f.total_price) AS monthly_sales
FROM fact_table f
JOIN time_dim t ON f.time_key = t.time_key
GROUP BY t.month;
GO

--3. Average transaction value for each store
CREATE OR ALTER VIEW vw_avg_transaction_per_store AS
SELECT f.store_key,
       ROUND(AVG(f.total_price),2) AS avg_transaction_value
FROM fact_table f
GROUP BY f.store_key;
GO

--4. Store with highest total revenue
CREATE OR ALTER VIEW vw_top_store_by_sales AS
SELECT TOP 1 s.store_key,
       SUM(f.total_price) AS total_sales
FROM fact_table f
JOIN store_dim s ON f.store_key = s.store_key
GROUP BY s.store_key
ORDER BY total_sales DESC;
GO

--5. Customers with highest total spending
CREATE OR ALTER VIEW vw_top_customers_by_spending AS
SELECT c.name,
       SUM(f.total_price) AS total_spent
FROM fact_table f
JOIN customer_dim c ON f.coustomer_key= c.coustomer_key
GROUP BY c.name;
GO

--6. Average total spending per customer
CREATE OR ALTER VIEW vw_avg_spending_per_customer AS
SELECT ROUND(AVG(customer_total),2) AS avg_customer_spending
FROM
(
    SELECT coustomer_key,
           SUM(total_price) AS customer_total
    FROM fact_table
    GROUP BY coustomer_key
) AS customer_summary;
GO

--7. Products with highest total quantity sold
CREATE OR ALTER VIEW vw_top_products_by_quantity AS
SELECT i.item_name,
       SUM(f.quantity) AS total_quantity_sold
FROM fact_table f
JOIN item_dim i ON f.item_key = i.item_key
GROUP BY i.item_name;
GO

--8. Total sales amount per product country
CREATE OR ALTER VIEW vw_sales_by_product_country AS
SELECT i.man_country,
       SUM(f.total_price) AS category_sales
FROM fact_table f
JOIN item_dim i ON f.item_key = i.item_key
GROUP BY i.man_country;
GO

--9. Total monthly sales for each store
CREATE OR ALTER VIEW vw_monthly_sales_per_store AS
SELECT s.store_key,
       t.month,
       SUM(f.total_price) AS total_sales
FROM fact_table f
JOIN store_dim s ON f.store_key = s.store_key
JOIN time_dim t ON f.time_key = t.time_key
GROUP BY s.store_key, t.month;
GO

--10. Products with total quantity sold > 100 units
CREATE OR ALTER VIEW vw_products_over_100_units AS
SELECT i.item_name,
       SUM(f.quantity) AS total_quantity_sold
FROM fact_table f
JOIN item_dim i ON f.item_key = i.item_key
GROUP BY i.item_name
HAVING SUM(f.quantity) > 100;
GO

--11. Number of transactions per store
CREATE OR ALTER VIEW vw_transactions_per_store AS
SELECT s.store_key,
       COUNT(*) AS total_transactions
FROM fact_table f
JOIN store_dim s ON f.store_key = s.store_key
GROUP BY s.store_key
;
GO

--12. Total sales per year
CREATE OR ALTER VIEW vw_yearly_sales AS
SELECT t.year,
       SUM(f.total_price) AS yearly_sales
FROM fact_table f
JOIN time_dim t ON f.time_key = t.time_key
GROUP BY t.year
;
GO

--13. Customers with highest number of transactions
CREATE OR ALTER VIEW vw_customers_by_transactions AS
SELECT c.name,
       COUNT(*) AS total_transactions
FROM fact_table f
JOIN customer_dim c ON f.coustomer_key = c.coustomer_key
GROUP BY c.name
;
GO

--14. Customers by number of transactions (key)
CREATE OR ALTER VIEW vw_customers_by_transactions_key AS
SELECT c.coustomer_key,
       COUNT(*) AS total_transactions
FROM fact_table f
JOIN customer_dim c ON f.coustomer_key = c.coustomer_key
GROUP BY c.coustomer_key
;
GO

--15. Months with sales above average
CREATE OR ALTER VIEW vw_months_above_avg_sales AS
SELECT t.month,
       SUM(f.total_price) AS monthly_sales
FROM fact_table f
JOIN time_dim t ON f.time_key = t.time_key
GROUP BY t.month
HAVING SUM(f.total_price) >
(
    SELECT AVG(monthly_total)
    FROM
    (
        SELECT SUM(total_price) AS monthly_total
        FROM fact_table f2
        JOIN time_dim t2 ON f2.time_key = t2.time_key
        GROUP BY t2.month
    ) AS monthly_summary
)
;
GO

--16. Total sales per customer (Window Function)
CREATE OR ALTER VIEW vw_total_sales_per_customer AS
SELECT 
    coustomer_key,
    total_price,
    SUM(total_price) OVER (PARTITION BY coustomer_key) AS total_sales_per_customer
FROM fact_table
;
GO

--17. Ranking customers by total sales (Window Function)
CREATE OR ALTER VIEW vw_customer_rank AS
SELECT 
    coustomer_key,
    SUM(total_price) AS total_sales,
    RANK() OVER (
        ORDER BY SUM(total_price) DESC, coustomer_key ASC
    ) AS customer_rank
FROM fact_table
GROUP BY coustomer_key
;
GO

--18. Running total of sales (Window Function)
CREATE OR ALTER VIEW vw_running_total_sales AS
SELECT 
    time_key,
    payment_key,
    total_price,
    SUM(total_price) OVER (
        ORDER BY time_key, payment_key
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS running_total_sales
FROM fact_table
;
GO

--19. Average selling price per product (Window Function)
CREATE OR ALTER VIEW vw_avg_selling_price_per_product AS
SELECT 
    item_key,
    total_price,
    AVG(total_price) OVER (PARTITION BY item_key) AS avg_item_price
FROM fact_table
;
GO

--20. Highest purchase transaction per customer (Window Function)
CREATE OR ALTER VIEW vw_highest_purchase_per_customer AS
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY coustomer_key ORDER BY total_price DESC) AS rn
    FROM fact_table
) t
WHERE rn = 1;
GO

--21. Ranking transactions within each store (Window Function)
CREATE OR ALTER VIEW vw_store_transaction_rank AS
SELECT 
    store_key,
    payment_key,
    total_price,
    DENSE_RANK() OVER (
        PARTITION BY store_key 
        ORDER BY total_price DESC, payment_key
    ) AS store_sales_rank
FROM fact_table;
GO

--22. Difference from previous transaction per customer (Window Function)
CREATE OR ALTER VIEW vw_diff_prev_transaction AS
SELECT 
    coustomer_key,
    time_key,
    payment_key,
    total_price,
    total_price - LAG(total_price) OVER (
        PARTITION BY coustomer_key 
        ORDER BY time_key, payment_key
    ) AS diff_from_prev_order
FROM fact_table;
GO

--23. Top 3 sales-contributing transactions per store (Window Function)
CREATE OR ALTER VIEW vw_top3_sales_per_store AS
SELECT *
FROM (
    SELECT 
        store_key,
        payment_key,
        total_price,
        total_price * 1.0 /
        SUM(total_price) OVER (PARTITION BY store_key) AS sales_ratio_in_store,
        DENSE_RANK() OVER (
            PARTITION BY store_key 
            ORDER BY total_price DESC
        ) AS sales_rank
    FROM fact_table
) t
WHERE sales_rank <= 3;
GO